---
name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Prepare Git info
        run: ./bin/gitinfo
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: beginner-cfop.tex
          latexmk_shell_escape: true
      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: beginner-cfop.pdf
